openapi: 3.0.0
info:
  title: User API
  version: 1.0.0
paths:
  /user:
    get:
      summary: Get user information
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  name:
                    type: string
                    example: John Doe
