openapi: 3.0.3
info:
  title: User API
  version: 1.0.0
paths:
  /user/1:
    get:
      summary: Get user details
      description: Returns user information
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: John Doe
      required:
        - id
        - name